### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [daviludvig/ludvig-theme-zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by daviludvig** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.
> 
> Please add a license file - if you don't have one in mind, I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.
> 
> Thanks!

Im doing it right now. Im telling you when its finished, ty for the attention!

**Comment by daviludvig** [comment]
> I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.
> 
> Please add a license file - if you don't have one in mind, I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.
> 
> Thanks!

Did it mate! Tell me if i have to change anything, i appreciate the acknowledgment.

**Comment by unixorn** [comment]
Thanks!
